### ISSUE TITLE
RoR Group Project

### ISSUE THREAD

**Issue by franclobo** [Emmykage/Recipe_App#17]
## Recipe app

**- We are two members.** @franclobo and @Emmykage and have equally assigned these projects to the best of our knowledge.
here is the Kanban project link https://github.com/users/Emmykage/projects/2

>> A new member was recently added to our group @Draxeytina. 
>>The following is the new project link: https://github.com/users/Emmykage/projects/2

Happy codding ✌🏽

**Comment by emmanuellekamwa** [comment]
**STATUS: APPROVED 🍾✔🎉**
Hello @franclobo and @Emmykage 👋
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- You documented your work professionally.✔
- You asked for the changes in a polite and friendly way.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
